export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const GET_FORECAST_FAIL = 'GET_FORECAST_FAIL';
export const SEARCH_WEATHERCITY_INPUT = 'SEARCH_WEATHERCITY_INPUT';
export const SEARCH_WEATHERCOUNTRY_INPUT = 'SEARCH_WEATHERCOUNTRY_INPUT';
export const SEARCH_FORECASTCITY_INPUT = 'SEARCH_FORECASTCITY_INPUT';
export const SEARCH_FORECASTCOUNTRY_INPUT = 'SEARCH_FORECASTCOUNTRY_INPUT';
